In [5]:
import numpy as np

a = np.matrix([1,2,3])
b = np.matrix([4,5,6])

print(a+b)

[[5 7 9]]


In [3]:
#cara panjang cik
def add(a,b):
    result=[]
    for first, second in zip(a,b):
        result.append(first+second)
    return result

add([1,2,3],[4,5,6])

[5, 7, 9]

In [6]:
import numpy as np
myArray=np.array([1,2,3,4])
yourArray=np.array([5,6,7,8])

print(myArray+yourArray)

[ 6  8 10 12]


In [8]:
import numpy as np

nilaiSiswa=np.array([55,43,98,76,65,77,65,90])

print(f"Nilai median: {np.median(nilaiSiswa)}")
print(f"Nilai minimal: {np.min(nilaiSiswa)}")
print(f"Nilai maksimal: {np.max(nilaiSiswa)}")
print(f"Nilai rata-rata: {np.average(nilaiSiswa)}")
print(f"Total nilai: {np.sum(nilaiSiswa)}")
print(f"Standar deviasi: {np.std(nilaiSiswa)}")

Nilai median: 70.5
Nilai minimal: 43
Nilai maksimal: 98
Nilai rata-rata: 71.125
Total nilai: 569
Standar deviasi: 16.81842367762211


In [ ]:
dir(np) #cek fungsi yang tersedia di lib numpy

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [10]:
a=np.zeros(5)
b=np.ones(3)
c=np.arange(1,10,2)

print(a)
print(b)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[1 3 5 7 9]


In [13]:
import numpy as np
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

In [15]:
import numpy as np
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print("Matriks awal: ")
print(a)

aTrans=a.transpose()
print("Hasil Transpose matriks: ")
print(aTrans)

Matriks awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Hasil Transpose matriks: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [21]:
import numpy as np
a=np.matrix([[1,2,3],
           [4,5,6],
           [7,8,9]])
b=np.matrix([[7,8,9],
           [4,5,6],
           [1,2,3]])
print("Matriks A dan B")
print("Matriks A:")
print(a)
print("Matriks B:")
print(b)

kali=a*b
print("Hasil kali matriks: ")
print(kali)

Matriks A dan B
Matriks A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks B:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
Hasil kali matriks: 
[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


In [ ]:
import numpy as np
data=np.array([102,105,110,107,111,115,120])

print("Saham selama 7 hari")
print(data)
print(f"Rata-rata saham: {np.average(data)}")
print(f"Perubahan saham harian: {np.diff(data)}")
print(f"Volatilitas saham: {np.std(data):.2f}")



Saham selama 7 hari
[102 105 110 107 111 115 120]
Rata-rata saham: 110.0
Perubahan saham harian: [ 3  5 -3  4  4  5]
Volatilitas saham: 5.66


In [ ]:
import numpy as np

data=np.array([12,5,8,10,3])
print("Data berat paket")
print(data)
print(f"Total berat paket: {np.sum(data)}")

In [34]:
import numpy as np
SA=np.array([[34,43,73],[82,22,12],[53,94,66]])
print("Data")
print(SA)
#a
print("Hapus kolom kedua")
print(np.delete(SA, 1, axis=1))
#b
tambah=np.array([[10,10,10]])
print(np.insert(SA, 1, tambah, 1))


Data
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Hapus kolom kedua
[[34 73]
 [82 12]
 [53 66]]
[[34 10 43 73]
 [82 10 22 12]
 [53 10 94 66]]


In [36]:
import numpy as np

a=np.matrix([[10,12],
             [8,15],
             [20,5]])
b=np.matrix([[5,7],
             [6,2],
             [10,3]])
total=a+b
print("Matriks A tambah matriks B")
print(total)
print("Total pengiriman harian") #baris
print(np.sum(total, axis=1))
print("Total pengiriman ke setiap tujuan") #kolom
print(np.sum(total, axis=0))

Matriks A tambah matriks B
[[15 19]
 [14 17]
 [30  8]]
Total pengiriman harian
[[34]
 [31]
 [38]]
Total pengiriman ke setiap tujuan
[[59 44]]


In [45]:
import numpy as np
a=np.array([[3,1],
            [2,4]])
b=np.array([29,38])
x=np.linalg.solve(a,b) #tadi nyoba kalau datanya matrix gx iso
print(f"Jumlah paket tipe 1: {x[0]}")
print(f"Jumlah paket tipe 2: {x[1]:.1f}")



Jumlah paket tipe 1: 7.8
Jumlah paket tipe 2: 5.6
